Repository harusari-chainware/harusari-chainware-spring, pull requests merged in 2025-07, with the labels that each got.

#120 feat : 발주 입고 기능 구현
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/exception/purchase/PurchaseOrderErrorCode.java
  src/main/java/com/harusari/chainware/purchase/command/application/controller/PurchaseOrderCommandController.java
  src/main/java/com/harusari/chainware/purchase/command/application/service/PurchaseOrderCommandService.java
  src/main/java/com/harusari/chainware/purchase/command/application/service/PurchaseOrderCommandServiceImpl.java
  src/main/java/com/harusari/chainware/purchase/command/domain/aggregate/PurchaseOrder.java
  src/main/java/com/harusari/chainware/purchase/command/domain/repository/PurchaseOrderDetailRepository.java
  src/main/java/com/harusari/chainware/warehouse/command/domain/aggregate/WarehouseInbound.java
  src/main/java/com/harusari/chainware/warehouse/command/domain/repository/WarehouseInboundRepository.java
  src/main/java/com/harusari/chainware/warehouse/command/domain/repository/WarehouseInventoryRepository.java
Labels: 🤖 기능

#128 refactor: 창고 주소를 우편번호, 도로명 주소, 상세 주소로 세분화
  src/main/java/com/harusari/chainware/member/command/application/dto/request/warehouse/WarehouseCreateRequest.java
  src/main/java/com/harusari/chainware/vendor/command/application/service/VendorCommandService.java
  src/main/java/com/harusari/chainware/vendor/command/application/service/VendorCommandServiceImpl.java
  src/main/java/com/harusari/chainware/warehouse/command/application/dto/request/WarehouseUpdateRequest.java
  src/main/java/com/harusari/chainware/warehouse/command/application/dto/response/WarehouseCommandResponse.java
  src/main/java/com/harusari/chainware/warehouse/command/application/service/WarehouseCommandServiceImpl.java
  src/main/java/com/harusari/chainware/warehouse/command/domain/aggregate/Warehouse.java
  src/main/java/com/harusari/chainware/warehouse/common/mapstruct/WarehouseMapStruct.java
  src/test/java/com/harusari/chainware/warehouse/command/application/controller/WarehouseCommandControllerTest.java
  src/test/java/com/harusari/chainware/warehouse/command/application/service/WarehouseCommandServiceImplTest.java
Labels: ♻️ 리팩토링, ✔️ 테스트

#136 feat: 재고 관련 조회 기능 구현 및 입고·품의 로직 개선
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/delivery/query/dto/request/DeliverySearchRequest.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryDetailResponse.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliverySearchResponse.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/FranchiseInfo.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/WarehouseInfo.java
  src/main/java/com/harusari/chainware/delivery/query/repository/DeliveryQueryRepositoryImpl.java
  src/main/java/com/harusari/chainware/exception/purchase/PurchaseOrderErrorCode.java
  src/main/java/com/harusari/chainware/purchase/command/application/controller/PurchaseOrderCommandController.java
  src/main/java/com/harusari/chainware/purchase/command/application/dto/request/PurchaseInboundItem.java
  src/main/java/com/harusari/chainware/purchase/command/application/dto/request/PurchaseInboundRequest.java
  src/main/java/com/harusari/chainware/purchase/command/application/service/PurchaseOrderCommandService.java
  src/main/java/com/harusari/chainware/purchase/command/application/service/PurchaseOrderCommandServiceImpl.java
  src/main/java/com/harusari/chainware/takeback/query/controller/TakeBackQueryController.java
  src/main/java/com/harusari/chainware/takeback/query/dto/request/TakeBackSearchRequest.java
  src/main/java/com/harusari/chainware/takeback/query/dto/response/OrderInfo.java
  src/main/java/com/harusari/chainware/takeback/query/dto/response/TakeBackBasicInfo.java
  src/main/java/com/harusari/chainware/takeback/query/dto/response/TakeBackDetailResponse.java
  src/main/java/com/harusari/chainware/takeback/query/dto/response/TakeBackProductInfo.java
  src/main/java/com/harusari/chainware/takeback/query/dto/response/TakeBackSearchResponse.java
  src/main/java/com/harusari/chainware/takeback/query/repository/TakeBackQueryRepository.java
  src/main/java/com/harusari/chainware/takeback/query/repository/TakeBackQueryRepositoryCustom.java
  src/main/java/com/harusari/chainware/takeback/query/repository/TakeBackQueryRepositoryImpl.java
  src/main/java/com/harusari/chainware/takeback/query/service/TakeBackQueryService.java
  src/main/java/com/harusari/chainware/takeback/query/service/TakeBackQueryServiceImpl.java
  src/main/java/com/harusari/chainware/vendor/query/dto/VendorDetailDto.java
  src/main/java/com/harusari/chainware/warehouse/command/domain/aggregate/WarehouseInbound.java
  src/main/java/com/harusari/chainware/warehouse/query/controller/WarehouseQueryController.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/request/WarehouseInventorySearchRequest.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/request/WarehouseSearchRequest.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/InboundHistory.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/InboundHistoryInfo.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/InventorySimpleInfo.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/OutboundHistory.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/OutboundHistoryInfo.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/ProductSimpleInfo.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/WarehouseBasicInfo.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/WarehouseDetailResponse.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/WarehouseInventoryDetailResponse.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/WarehouseInventoryInfo.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/WarehouseSearchResponse.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/WarehouseSimpleInfo.java
  src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseInventoryQueryRepository.java
  src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseInventoryQueryRepositoryCustom.java
  src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseInventoryQueryRepositoryImpl.java
  src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseQueryRepository.java
  src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseQueryRepositoryCustom.java
  src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseQueryRepositoryImpl.java
  src/main/java/com/harusari/chainware/warehouse/query/service/WarehouseQueryService.java
  src/main/java/com/harusari/chainware/warehouse/query/service/WarehouseQueryServiceImpl.java
  src/main/resources/mappers/vendor/VendorQueryMapper.xml
Labels: 🔨 수정, 🤖 기능

#141 feat: 재고 관련 로직 개선 및 Swagger 적용
  src/main/java/com/harusari/chainware/common/infrastructure/storage/S3Uploader.java
  src/main/java/com/harusari/chainware/common/infrastructure/storage/StorageUploader.java
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/delivery/command/application/controller/DeliveryCommandController.java
  src/main/java/com/harusari/chainware/delivery/command/application/service/DeliveryCommandService.java
  src/main/java/com/harusari/chainware/delivery/command/application/service/DeliveryCommandServiceImpl.java
  src/main/java/com/harusari/chainware/delivery/command/domain/repository/DeliveryRepository.java
  src/main/java/com/harusari/chainware/delivery/exception/DeliveryErrorCode.java
  src/main/java/com/harusari/chainware/delivery/query/controller/DeliveryQueryController.java
  src/main/java/com/harusari/chainware/order/command/application/controller/OrderCommandController.java
  src/main/java/com/harusari/chainware/order/command/application/dto/request/OrderCreateRequest.java
  src/main/java/com/harusari/chainware/order/command/application/service/OrderCommandServiceImpl.java
  src/main/java/com/harusari/chainware/order/exception/OrderErrorCode.java
  src/main/java/com/harusari/chainware/order/query/controller/OrderQueryController.java
  src/main/java/com/harusari/chainware/order/query/controller/OrderWarehouseQueryController.java
  src/main/java/com/harusari/chainware/order/query/dto/response/AvailableWarehouseResponse.java
  src/main/java/com/harusari/chainware/order/query/dto/response/RiskyProductInfo.java
  src/main/java/com/harusari/chainware/order/query/service/OrderWarehouseQueryServiceImpl.java
  src/main/java/com/harusari/chainware/takeback/command/application/controller/TakeBackCommandController.java
  src/main/java/com/harusari/chainware/takeback/command/application/dto/request/TakeBackCreateRequest.java
  src/main/java/com/harusari/chainware/takeback/command/application/service/TakeBackCommandService.java
  src/main/java/com/harusari/chainware/takeback/command/application/service/TakeBackCommandServiceImpl.java
  src/main/java/com/harusari/chainware/takeback/exception/TakeBackErrorCode.java
  src/main/java/com/harusari/chainware/takeback/query/controller/TakeBackQueryController.java
  src/main/java/com/harusari/chainware/takeback/query/repository/TakeBackQueryRepositoryImpl.java
  src/main/java/com/harusari/chainware/warehouse/command/application/controller/WarehouseCommandController.java
  src/main/java/com/harusari/chainware/warehouse/command/application/service/WarehouseCommandService.java
  src/main/java/com/harusari/chainware/warehouse/command/application/service/WarehouseCommandServiceImpl.java
  src/main/java/com/harusari/chainware/warehouse/command/domain/repository/WarehouseInventoryRepository.java
  src/main/java/com/harusari/chainware/warehouse/exception/WarehouseErrorCode.java
  src/main/java/com/harusari/chainware/warehouse/query/controller/WarehouseQueryController.java
  src/test/java/com/harusari/chainware/delivery/command/application/controller/DeliveryCommandControllerTest.java
  src/test/java/com/harusari/chainware/delivery/command/application/service/DeliveryCommandServiceImplTest.java
  src/test/java/com/harusari/chainware/order/command/application/controller/OrderCommandControllerTest.java
  src/test/java/com/harusari/chainware/order/command/application/service/OrderCommandServiceImplTest.java
  src/test/java/com/harusari/chainware/warehouse/command/application/controller/WarehouseCommandControllerTest.java
  src/test/java/com/harusari/chainware/warehouse/command/application/service/WarehouseCommandServiceImplTest.java
Labels: ♻️ 리팩토링, 🤖 기능

#143 feat: 회원 개인의 정보 조회, 수정 기능 구현
  src/main/java/com/harusari/chainware/auth/model/CustomUserDetails.java
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/member/command/application/controller/MemberCommandController.java
  src/main/java/com/harusari/chainware/member/command/application/dto/request/UpdateMyInfoRequest.java
  src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandService.java
  src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandServiceImpl.java
  src/main/java/com/harusari/chainware/member/command/domain/aggregate/Member.java
  src/main/java/com/harusari/chainware/member/query/controller/MemberQueryController.java
  src/main/java/com/harusari/chainware/member/query/dto/response/MyMemberDetailResponse.java
  src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryCustom.java
  src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryImpl.java
  src/main/java/com/harusari/chainware/member/query/service/MemberQueryService.java
  src/main/java/com/harusari/chainware/member/query/service/MemberQueryServiceImpl.java
Labels: ♻️ 리팩토링, 🤖 기능

#153 docs: 가맹점 controller에 스웨거 어노테이션 적용
  src/main/java/com/harusari/chainware/franchise/command/application/controller/FranchiseCommandController.java
  src/main/java/com/harusari/chainware/franchise/query/controller/FranchiseQueryController.java
Labels: 📝 문서

#155 refactor: 가맹점 수정 기능에 계약 시작일, 종료일을 변경하는 기능 구현
  src/main/java/com/harusari/chainware/franchise/command/application/dto/request/UpdateFranchiseRequest.java
  src/main/java/com/harusari/chainware/franchise/command/application/service/FranchiseCommandServiceImpl.java
  src/main/java/com/harusari/chainware/franchise/command/domain/aggregate/Franchise.java
  src/test/java/com/harusari/chainware/franchise/command/application/service/FranchiseCommandServiceImplTest.java
  src/test/java/com/harusari/chainware/franchise/command/domain/aggregate/FranchiseTest.java
Labels: ♻️ 리팩토링

#164 refactor: CORS 설정 및 브라우저 정보를 가져오는 로직 수정
  build.gradle
  src/main/java/com/harusari/chainware/auth/service/AuthServiceImpl.java
  src/main/java/com/harusari/chainware/config/security/SecurityConfig.java
  src/main/java/com/harusari/chainware/member/common/utils/UserAgentUtils.java
Labels: ♻️ 리팩토링, 🐞 버그

#168 refactor : 프론트 연동을 위한 조회 기능 수정
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/exception/purchase/PurchaseOrderErrorCode.java
  src/main/java/com/harusari/chainware/purchase/command/application/service/PurchaseOrderCommandServiceImpl.java
  src/main/java/com/harusari/chainware/purchase/command/domain/aggregate/PurchaseOrder.java
  src/main/java/com/harusari/chainware/purchase/query/controller/PurchaseOrderQueryController.java
  src/main/java/com/harusari/chainware/purchase/query/dto/MemberInfo.java
  src/main/java/com/harusari/chainware/purchase/query/dto/PWarehouseInfo.java
  src/main/java/com/harusari/chainware/purchase/query/dto/PurchaseOrderDetailResponse.java
  src/main/java/com/harusari/chainware/purchase/query/dto/PurchaseOrderInfo.java
  src/main/java/com/harusari/chainware/purchase/query/dto/PurchaseOrderSearchCondition.java
  src/main/java/com/harusari/chainware/purchase/query/dto/PurchaseOrderSummaryResponse.java
  src/main/java/com/harusari/chainware/purchase/query/dto/VendorInfo.java
  src/main/java/com/harusari/chainware/purchase/query/service/PurchaseOrderQueryServiceImpl.java
  src/main/java/com/harusari/chainware/requisition/command/application/dto/request/CreateRequisitionRequest.java
  src/main/java/com/harusari/chainware/requisition/command/application/service/RequisitionCommandServiceImpl.java
  src/main/java/com/harusari/chainware/requisition/command/domain/aggregate/Requisition.java
  src/main/java/com/harusari/chainware/requisition/query/controller/RequisitionQueryController.java
  src/main/java/com/harusari/chainware/requisition/query/dto/response/RequisitionDetailResponse.java
  src/main/java/com/harusari/chainware/requisition/query/dto/response/RequisitionInfo.java
  src/main/java/com/harusari/chainware/requisition/query/dto/response/RequisitionItemInfo.java
  src/main/java/com/harusari/chainware/requisition/query/dto/response/RequisitionSummaryView.java
  src/main/java/com/harusari/chainware/requisition/query/mapper/RequisitionQueryMapper.java
  src/main/java/com/harusari/chainware/requisition/query/service/RequisitionQueryService.java
  src/main/java/com/harusari/chainware/requisition/query/service/RequisitionQueryServiceImpl.java
  src/main/java/com/harusari/chainware/warehouse/command/domain/aggregate/WarehouseInbound.java
  src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseQueryRepositoryCustom.java
  src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseQueryRepositoryImpl.java
  src/main/java/com/harusari/chainware/warehouse/query/service/WarehouseQueryService.java
  src/main/java/com/harusari/chainware/warehouse/query/service/WarehouseQueryServiceImpl.java
  src/main/resources/mappers/purchase_order/PurchaseOrderQueryMapper.xml
  src/main/resources/mappers/requisition/RequisitionQueryMapper.xml
Labels: ♻️ 리팩토링

#175 refactor: 회원 조회 쿼리에 탈퇴 여부 옵션 추가
  src/main/java/com/harusari/chainware/exception/auth/AuthErrorCode.java
  src/main/java/com/harusari/chainware/member/query/dto/request/MemberSearchRequest.java
  src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryImpl.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ♻️ 리팩토링, ⚙ 설정

#178 feat: 거래처 계약 정보 조회 기능 구현
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/vendor/query/controller/VendorQueryController.java
  src/main/java/com/harusari/chainware/vendor/query/dto/response/VendorContractInfoResponse.java
  src/main/java/com/harusari/chainware/vendor/query/dto/response/VendorPresignedUrlResponse.java
  src/main/java/com/harusari/chainware/vendor/query/repository/VendorQueryRepositoryCustom.java
  src/main/java/com/harusari/chainware/vendor/query/repository/VendorQueryRepositoryImpl.java
  src/main/java/com/harusari/chainware/vendor/query/service/VendorQueryService.java
  src/main/java/com/harusari/chainware/vendor/query/service/VendorQueryServiceImpl.java
Labels: 🤖 기능

#182 refactor: 주문 조회 및 등록에 대한 API 수정
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/order/command/application/service/OrderCommandServiceImpl.java
  src/main/java/com/harusari/chainware/order/exception/OrderErrorCode.java
  src/main/java/com/harusari/chainware/order/query/controller/OrderQueryController.java
  src/main/java/com/harusari/chainware/order/query/dto/response/DeliveryHistoryInfo.java
  src/main/java/com/harusari/chainware/order/query/dto/response/MyFranchiseResponse.java
  src/main/java/com/harusari/chainware/order/query/dto/response/OrderSearchResponse.java
  src/main/java/com/harusari/chainware/order/query/repository/OrderQueryRepositoryCustom.java
  src/main/java/com/harusari/chainware/order/query/repository/OrderQueryRepositoryImpl.java
  src/main/java/com/harusari/chainware/order/query/service/OrderQueryService.java
  src/main/java/com/harusari/chainware/order/query/service/OrderQueryServiceImpl.java
Labels: ♻️ 리팩토링, 🤖 기능

#187 refactor : 품의 / 발주 프론트 연동을 위한 코드 수정
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/purchase/query/dto/PurchaseOrderProductResponse.java
  src/main/java/com/harusari/chainware/purchase/query/dto/PurchaseOrderSearchCondition.java
  src/main/java/com/harusari/chainware/purchase/query/mapper/PurchaseOrderQueryMapper.java
  src/main/java/com/harusari/chainware/requisition/query/dto/request/RequisitionSearchCondition.java
  src/main/resources/mappers/purchase_order/PurchaseOrderQueryMapper.xml
  src/main/resources/mappers/requisition/RequisitionQueryMapper.xml
Labels: ♻️ 리팩토링

#191 fix: 회원 목록 조회 count 쿼리에 position, isDeleted 조건 추가
  src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryImpl.java
Labels: 🐞 버그

#193 refactor: 거래처 상태 기본 값을 IN_PROGRESS로 설정
  src/main/java/com/harusari/chainware/vendor/command/domain/aggregate/Vendor.java
Labels: ♻️ 리팩토링

#195 feat: 헬스체크 API 추가 및 Redis SSL 프로퍼티명 수정
  src/main/java/com/harusari/chainware/common/controller/HealthCheckController.java
  src/main/java/com/harusari/chainware/config/RedisConfig.java
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
Labels: 🐞 버그, 🤖 기능

#197 ci: Github Actions 기반 ECS 배포 파이프라인 추가
  .github/workflows/ecs-deploy.yml
  .github/workflows/run-tests-on-pr.yml
Labels: 🔗 ci/cd

#201 fix: 환경별 쿠키 옵션 동적 처리 기능 추가
  src/main/java/com/harusari/chainware/auth/controller/AuthController.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🐞 버그

#213 refactor: CORS 허용 Origin을 환경변수 기반으로 개발·운영 환경 분리
  src/main/java/com/harusari/chainware/config/security/SecurityConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ♻️ 리팩토링

#215 refactor : 품의 / 발주 추가 기능 마무리
  src/main/java/com/harusari/chainware/purchase/query/controller/PurchaseOrderQueryController.java
  src/main/java/com/harusari/chainware/purchase/query/dto/PurchaseOrderListResponse.java
  src/main/java/com/harusari/chainware/purchase/query/mapper/PurchaseOrderQueryMapper.java
  src/main/java/com/harusari/chainware/purchase/query/service/PurchaseOrderQueryService.java
  src/main/java/com/harusari/chainware/purchase/query/service/PurchaseOrderQueryServiceImpl.java
  src/main/java/com/harusari/chainware/requisition/query/controller/RequisitionQueryController.java
  src/main/java/com/harusari/chainware/requisition/query/dto/response/RequisitionListResponse.java
  src/main/java/com/harusari/chainware/requisition/query/mapper/RequisitionQueryMapper.java
  src/main/java/com/harusari/chainware/requisition/query/service/RequisitionQueryService.java
  src/main/java/com/harusari/chainware/requisition/query/service/RequisitionQueryServiceImpl.java
  src/main/resources/mappers/purchase_order/PurchaseOrderQueryMapper.xml
  src/main/resources/mappers/requisition/RequisitionQueryMapper.xml
Labels: ♻️ 리팩토링

#216 fix: 프론트 페이지 구현을 위한 로직 수정
  src/main/java/com/harusari/chainware/statistics/query/mapper/DisposalRateStatisticsQueryMapper.java
  src/main/java/com/harusari/chainware/statistics/query/service/disposal/DisposalRateStatisticsQueryServiceImpl.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/request/WarehouseInventorySearchRequest.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/OutboundHistory.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/ProductSimpleInfo.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/WarehouseSimpleInfo.java
  src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseInventoryQueryRepositoryImpl.java
  src/main/resources/mappers/statistics/DisposalRateStatisticsQueryMapper.xml
  src/main/resources/mappers/statistics/InventoryStatisticsMapper.xml
  src/main/resources/mappers/statistics/StoreOrderStatisticsQueryMapper.xml
Labels: 🔨 수정

#226 fix: 오류 로직 수정
  src/main/java/com/harusari/chainware/statistics/query/service/predictionComparison/PredictionComparisonQueryServiceImpl.java
  src/main/java/com/harusari/chainware/takeback/query/repository/TakeBackQueryRepositoryImpl.java
  src/main/resources/mappers/statistics/PredictionComparisonQueryMapper.xml
Labels: 🔨 수정

#228 refactor : 품의 등록 시 거래처 별 계약 품목 페이징 처리 오류 수정
  src/main/java/com/harusari/chainware/contract/query/controller/VendorProductContractQueryController.java
  src/main/java/com/harusari/chainware/contract/query/dto/response/VendorProductContractDto.java
  src/main/java/com/harusari/chainware/contract/query/dto/response/VendorProductContractListDto.java
  src/main/resources/mappers/contract/ContractQueryMapper.xml
Labels: ♻️ 리팩토링

#229 fix : 거래처 별 계약 품목 조회 오류 수정
  src/main/java/com/harusari/chainware/contract/query/dto/response/VendorProductContractDto.java
Labels: 🐞 버그

#232 fix: SecurityPolicy에 잘못 등록된 비밀번호 변경 엔드포인트 수정
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
Labels: 🐞 버그

#234 fix: warehouseSearchRequestDto에 warehouseId 추가
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/warehouse/query/controller/WarehouseQueryController.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/request/WarehouseInventorySearchRequest.java
  src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseInventoryQueryRepositoryImpl.java
Labels: 🔨 수정

#238 fix: 재고 상세 조회 시 동일한 출고 기록이 나오는 오류 수정
  src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseInventoryQueryRepositoryImpl.java
Labels: 🔨 수정

#246 fix: FranchiseInfo DTO 필드 순서에 맞게 QueryDSL 결과 매핑 순서 수정
  src/main/java/com/harusari/chainware/takeback/query/repository/TakeBackQueryRepositoryImpl.java
Labels: 🐞 버그

#248 refactor: 배송 조회 및 관리에 대한 DTO 수정
  src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryDetailInfo.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryDetailResponse.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryProductInfo.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryTakeBackInfo.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryTakeBackProductInfo.java
  src/main/java/com/harusari/chainware/delivery/query/repository/DeliveryQueryRepositoryImpl.java
Labels: 🤖 기능

#249 fix: FranchiseInfo DTO 필드 순서에 맞게 QueryDSL 결과 매핑 순서 수정 (#247)
  src/main/java/com/harusari/chainware/takeback/query/repository/TakeBackQueryRepositoryImpl.java
Labels: 🔨 수정

#251 fix: 창고 목록 조회와 재고 상세 조회에 safetyQuantity 추가
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/InventorySimpleInfo.java
  src/main/java/com/harusari/chainware/warehouse/query/dto/response/WarehouseInventoryInfo.java
  src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseInventoryQueryRepositoryImpl.java
Labels: 🔨 수정
