Repository harusari-chainware/harusari-chainware-spring, pull requests merged in 2025-06, with the labels that each got.

#4 feat: CQRS 기반의 회원 도메인 클래스 및 인터페이스 구조 초기 생성
  src/main/java/com/harusari/chainware/config/SwaggerConfig.java
  src/main/java/com/harusari/chainware/member/command/application/controller/MemberCommandController.java
  src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandService.java
  src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandServiceImpl.java
  src/main/java/com/harusari/chainware/member/command/domain/aggregate/Member.java
  src/main/java/com/harusari/chainware/member/command/domain/repository/MemberRepository.java
  src/main/java/com/harusari/chainware/member/command/infrastructure/repository/JpaMemberRepository.java
  src/main/java/com/harusari/chainware/member/query/controller/MemberQueryController.java
  src/main/java/com/harusari/chainware/member/query/mapper/MemberMapper.java
  src/main/java/com/harusari/chainware/member/query/service/MemberQueryService.java
  src/main/java/com/harusari/chainware/member/query/service/MemberQueryServiceImpl.java
Labels: ⚙ 설정, 🤖 기능

#10 feat: mapstruct 라이브러리 추가 및 application.yml 불필요한 설정 삭제
  build.gradle
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ♻️ 리팩토링, ⚙ 설정

#11 fix: vendorContact 제거
  src/main/java/com/harusari/chainware/statistics/query/controller/MenuSalesQueryController.java
  src/main/java/com/harusari/chainware/statistics/query/dto/MenuSalesResponse.java
  src/main/java/com/harusari/chainware/statistics/query/mapper/MenuSalesMapper.java
  src/main/java/com/harusari/chainware/statistics/query/service/MenuSalesQueryService.java
  src/main/java/com/harusari/chainware/statistics/query/service/MenuSalesQueryServiceImpl.java
  src/main/java/com/harusari/chainware/vendor/command/application/dto/VendorCreateRequestDto.java
  src/main/java/com/harusari/chainware/vendor/command/application/dto/VendorUpdateRequestDto.java
  src/main/java/com/harusari/chainware/vendor/command/application/service/VendorCommandServiceImpl.java
  src/main/java/com/harusari/chainware/vendor/command/domain/aggregate/Vendor.java
  src/main/java/com/harusari/chainware/vendor/query/dto/VendorDetailDto.java
  src/main/java/com/harusari/chainware/vendor/query/dto/VendorListDto.java
  src/main/resources/mappers/statistics/MenuSalesMapper.xml
  src/main/resources/mappers/vendor/VendorQueryMapper.xml
Labels: ♻️ 리팩토링, 🤖 기능

#14 feat: 수요 예측을 위한 통계 조회
  src/main/java/com/harusari/chainware/statistics/query/controller/MenuSalesQueryController.java
  src/main/java/com/harusari/chainware/statistics/query/controller/SalesPatternQueryController.java
  src/main/java/com/harusari/chainware/statistics/query/dto/DailySalesResponse.java
  src/main/java/com/harusari/chainware/statistics/query/dto/HourlySalesResponse.java
  src/main/java/com/harusari/chainware/statistics/query/dto/WeekdaySalesResponse.java
  src/main/java/com/harusari/chainware/statistics/query/mapper/MenuSalesMapper.java
  src/main/java/com/harusari/chainware/statistics/query/mapper/SalesPatternMapper.java
  src/main/java/com/harusari/chainware/statistics/query/service/MenuSalesQueryService.java
  src/main/java/com/harusari/chainware/statistics/query/service/MenuSalesQueryServiceImpl.java
  src/main/java/com/harusari/chainware/statistics/query/service/SalesPatternQueryService.java
  src/main/java/com/harusari/chainware/statistics/query/service/SalesPatternQueryServiceImpl.java
  src/main/resources/mappers/statistics/MenuSalesMapper.xml
  src/main/resources/mappers/statistics/SalesPatternMapper.xml
Labels: 🤖 기능

#18 feat: 품의서 CRUD 기능 구현
  src/main/java/com/harusari/chainware/config/SecurityConfig.java
  src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandServiceImpl.java
  src/main/java/com/harusari/chainware/member/query/controller/MemberQueryController.java
  src/main/java/com/harusari/chainware/requisition/command/application/controller/RequisitionCommandController.java
  src/main/java/com/harusari/chainware/requisition/command/application/dto/request/CreateRequisitionRequest.java
  src/main/java/com/harusari/chainware/requisition/command/application/dto/request/RequisitionItemRequest.java
  src/main/java/com/harusari/chainware/requisition/command/application/exception/AccessDeniedException.java
  src/main/java/com/harusari/chainware/requisition/command/application/exception/InvalidStatusException.java
  src/main/java/com/harusari/chainware/requisition/command/application/exception/NotFoundException.java
  src/main/java/com/harusari/chainware/requisition/command/application/service/RequisitionCommandService.java
  src/main/java/com/harusari/chainware/requisition/command/application/service/RequisitionCommandServiceImpl.java
  src/main/java/com/harusari/chainware/requisition/command/domain/aggregate/RejectRequisitionRequest.java
  src/main/java/com/harusari/chainware/requisition/command/domain/aggregate/Requisition.java
  src/main/java/com/harusari/chainware/requisition/command/domain/aggregate/RequisitionDetail.java
  src/main/java/com/harusari/chainware/requisition/command/domain/aggregate/RequisitionStatus.java
  src/main/java/com/harusari/chainware/requisition/command/domain/repository/RequisitionDetailRepository.java
  src/main/java/com/harusari/chainware/requisition/command/domain/repository/RequisitionRepository.java
  src/main/java/com/harusari/chainware/requisition/command/infrastructure/RequisitionCodeGenerator.java
  src/main/java/com/harusari/chainware/requisition/query/controller/RequisitionQueryController.java
  src/main/java/com/harusari/chainware/requisition/query/dto/request/RequisitionSearchCondition.java
  src/main/java/com/harusari/chainware/requisition/query/dto/response/RequisitionDetailResponse.java
  src/main/java/com/harusari/chainware/requisition/query/dto/response/RequisitionItemResponse.java
  src/main/java/com/harusari/chainware/requisition/query/dto/response/RequisitionSummaryResponse.java
  src/main/java/com/harusari/chainware/requisition/query/mapper/RequisitionQueryMapper.java
  src/main/java/com/harusari/chainware/requisition/query/service/RequisitionQueryService.java
  src/main/java/com/harusari/chainware/requisition/query/service/RequisitionQueryServiceImpl.java
  src/main/resources/mappers/requisition/RequisitionQueryMapper.xml
Labels: 🤖 기능

#23 feat: 가맹점/창고/반품 폐기 등록 및 가맹점 관리자/창고 관리자/ 일반,책임 관리자 폐기 조회
  src/main/java/com/harusari/chainware/disposal/command/application/controller/DisposalCommandController.java
  src/main/java/com/harusari/chainware/disposal/command/application/dto/DisposalCommandRequestDto.java
  src/main/java/com/harusari/chainware/disposal/command/application/service/DisposalCommandService.java
  src/main/java/com/harusari/chainware/disposal/command/application/service/DisposalCommandServiceImpl.java
  src/main/java/com/harusari/chainware/disposal/command/domain/aggregate/Disposal.java
  src/main/java/com/harusari/chainware/disposal/command/domain/repository/DisposalRepository.java
  src/main/java/com/harusari/chainware/disposal/command/infrastructure/repository/JpaDisposalRepository.java
  src/main/java/com/harusari/chainware/disposal/query/controller/DisposalQueryController.java
  src/main/java/com/harusari/chainware/disposal/query/dto/DisposalListDto.java
  src/main/java/com/harusari/chainware/disposal/query/dto/DisposalListResponseDto.java
  src/main/java/com/harusari/chainware/disposal/query/dto/DisposalSearchRequestDto.java
  src/main/java/com/harusari/chainware/disposal/query/mapper/DisposalQueryMapper.java
  src/main/java/com/harusari/chainware/disposal/query/service/DisposalQueryService.java
  src/main/java/com/harusari/chainware/disposal/query/service/DisposalQueryServiceImpl.java
  src/main/java/com/harusari/chainware/franchise/command/domain/repository/FranchiseRepository.java
  src/main/java/com/harusari/chainware/warehouse/command/domain/repository/WarehouseRepository.java
  src/main/resources/mappers/disposal/DisposalQueryMapper.xml
Labels: 🤖 기능

#26 refactor: 회원 기능에서 command와 query를 명확하게 분리
  src/main/java/com/harusari/chainware/member/command/application/controller/MemberCommandController.java
  src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandService.java
  src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandServiceImpl.java
  src/main/java/com/harusari/chainware/member/command/domain/repository/AuthorityCommandRepository.java
  src/main/java/com/harusari/chainware/member/command/domain/repository/MemberCommandRepository.java
  src/main/java/com/harusari/chainware/member/command/infrastructure/repository/JpaAuthorityCommandRepository.java
  src/main/java/com/harusari/chainware/member/command/infrastructure/repository/JpaMemberCommandRepository.java
  src/main/java/com/harusari/chainware/member/common/constants/EmailValidationConstant.java
  src/main/java/com/harusari/chainware/member/query/controller/MemberQueryController.java
  src/main/java/com/harusari/chainware/member/query/mapper/MemberMapper.java
  src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepository.java
  src/main/java/com/harusari/chainware/member/query/service/MemberQueryService.java
  src/main/java/com/harusari/chainware/member/query/service/MemberQueryServiceImpl.java
Labels: ♻️ 리팩토링

#30 feat: 창고 기본 CRUD 기능 구현
  src/main/java/com/harusari/chainware/config/SecurityConfig.java
  src/main/java/com/harusari/chainware/warehouse/command/application/controller/WarehouseCommandController.java
  src/main/java/com/harusari/chainware/warehouse/command/application/dto/WarehouseInventoryCommandResponse.java
  src/main/java/com/harusari/chainware/warehouse/command/application/dto/request/WarehouseInventoryCreateRequest.java
  src/main/java/com/harusari/chainware/warehouse/command/application/dto/request/WarehouseInventoryUpdateRequest.java
  src/main/java/com/harusari/chainware/warehouse/command/application/dto/request/WarehouseUpdateRequest.java
  src/main/java/com/harusari/chainware/warehouse/command/application/dto/response/WarehouseCommandResponse.java
  src/main/java/com/harusari/chainware/warehouse/command/application/service/WarehouseCommandService.java
  src/main/java/com/harusari/chainware/warehouse/command/application/service/WarehouseCommandServiceImpl.java
  src/main/java/com/harusari/chainware/warehouse/command/domain/aggregate/Warehouse.java
  src/main/java/com/harusari/chainware/warehouse/command/domain/aggregate/WarehouseInventory.java
  src/main/java/com/harusari/chainware/warehouse/command/domain/repository/WarehouseInventoryRepository.java
  src/main/java/com/harusari/chainware/warehouse/command/infrastructure/repository/JpaWarehouseInventoryRepository.java
  src/main/java/com/harusari/chainware/warehouse/exception/WarehouseErrorCode.java
  src/main/java/com/harusari/chainware/warehouse/exception/WarehouseException.java
  src/main/java/com/harusari/chainware/warehouse/exception/handler/WarehouseExceptionHandler.java
Labels: 🤖 기능

#44 refactor: 회원 이메일 중복 확인 시 탈퇴 여부 조건 제거 및 회원 조회 쿼리에 탈퇴 여부 조건 추가
  src/main/java/com/harusari/chainware/auth/service/AuthServiceImpl.java
  src/main/java/com/harusari/chainware/auth/service/CustomUserDetailsService.java
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepository.java
  src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryCustom.java
  src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryImpl.java
Labels: ♻️ 리팩토링, 🐞 버그

#46 feat: 비밀번호 변경 기능 구현
  src/main/java/com/harusari/chainware/config/security/SecurityConfig.java
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/exception/member/InvalidCurrentPasswordException.java
  src/main/java/com/harusari/chainware/exception/member/InvalidPasswordChangeException.java
  src/main/java/com/harusari/chainware/exception/member/MemberErrorCode.java
  src/main/java/com/harusari/chainware/exception/member/PasswordConfirmationMismatchException.java
  src/main/java/com/harusari/chainware/exception/member/PasswordSameAsCurrentException.java
  src/main/java/com/harusari/chainware/exception/member/handler/MemberExceptionHandler.java
  src/main/java/com/harusari/chainware/member/command/application/controller/MemberCommandController.java
  src/main/java/com/harusari/chainware/member/command/application/dto/request/PasswordChangeRequest.java
  src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandService.java
  src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandServiceImpl.java
  src/main/java/com/harusari/chainware/member/command/domain/aggregate/Member.java
  src/main/java/com/harusari/chainware/member/command/domain/repository/MemberCommandRepositoryCustom.java
  src/main/java/com/harusari/chainware/member/command/infrastructure/repository/JpaMemberCommandRepository.java
  src/main/java/com/harusari/chainware/member/command/infrastructure/repository/MemberCommandRepositoryCustomImpl.java
Labels: 🤖 기능

#50 feat: 회원 정보 조회 기능 구현
  src/main/java/com/harusari/chainware/common/dto/PageResponse.java
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/member/query/controller/MemberQueryController.java
  src/main/java/com/harusari/chainware/member/query/dto/request/MemberSearchRequest.java
  src/main/java/com/harusari/chainware/member/query/dto/response/MemberSearchResponse.java
  src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryCustom.java
  src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryImpl.java
  src/main/java/com/harusari/chainware/member/query/service/MemberQueryService.java
  src/main/java/com/harusari/chainware/member/query/service/MemberQueryServiceImpl.java
Labels: 🤖 기능

#49 feat : 품의서 승인 시 자동 발주 등록 및 발주 목록 / 상세 조회 기능 구현
  src/main/java/com/harusari/chainware/config/security/SecurityConfig.java
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/purchase/command/application/service/PurchaseOrderCommandService.java
  src/main/java/com/harusari/chainware/purchase/command/application/service/PurchaseOrderCommandServiceImpl.java
  src/main/java/com/harusari/chainware/purchase/command/domain/aggregate/PurchaseOrder.java
  src/main/java/com/harusari/chainware/purchase/command/domain/aggregate/PurchaseOrderDetail.java
  src/main/java/com/harusari/chainware/purchase/command/domain/aggregate/PurchaseOrderStatus.java
  src/main/java/com/harusari/chainware/purchase/command/domain/repository/PurchaseOrderDetailRepository.java
  src/main/java/com/harusari/chainware/purchase/command/domain/repository/PurchaseOrderRepository.java
  src/main/java/com/harusari/chainware/purchase/command/infrastructure/PurchaseOrderCodeGenerator.java
  src/main/java/com/harusari/chainware/purchase/query/controller/PurchaseOrderQueryController.java
  src/main/java/com/harusari/chainware/purchase/query/dto/PurchaseOrderDetailResponse.java
  src/main/java/com/harusari/chainware/purchase/query/dto/PurchaseOrderProductResponse.java
  src/main/java/com/harusari/chainware/purchase/query/dto/PurchaseOrderSearchCondition.java
  src/main/java/com/harusari/chainware/purchase/query/dto/PurchaseOrderSummaryResponse.java
  src/main/java/com/harusari/chainware/purchase/query/mapper/PurchaseOrderQueryMapper.java
  src/main/java/com/harusari/chainware/purchase/query/service/PurchaseOrderQueryService.java
  src/main/java/com/harusari/chainware/purchase/query/service/PurchaseOrderQueryServiceImpl.java
  src/main/java/com/harusari/chainware/requisition/command/application/controller/RequisitionCommandController.java
  src/main/java/com/harusari/chainware/requisition/command/application/dto/request/CreateRequisitionRequest.java
  src/main/java/com/harusari/chainware/requisition/command/application/service/RequisitionCommandService.java
  src/main/java/com/harusari/chainware/requisition/command/application/service/RequisitionCommandServiceImpl.java
  src/main/java/com/harusari/chainware/requisition/command/domain/aggregate/RequisitionDetail.java
  src/main/java/com/harusari/chainware/requisition/command/infrastructure/CommonCodeGenerator.java
  src/main/java/com/harusari/chainware/requisition/command/infrastructure/RequisitionCodeGenerator.java
  src/main/java/com/harusari/chainware/requisition/query/controller/RequisitionQueryController.java
  src/main/java/com/harusari/chainware/requisition/query/dto/response/RequisitionDetailResponse.java
  src/main/resources/mappers/perchase_order/PurchaseOrderQueryMapper.xml
  src/main/resources/mappers/vendor/VendorQueryMapper.xml
Labels: 🤖 기능

#55 feat: 배송에 예외처리 및 테스트코드 작성
  src/main/java/com/harusari/chainware/config/security/SecurityConfig.java
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/delivery/command/application/dto/request/DeliveryStartRequest.java
  src/main/java/com/harusari/chainware/delivery/command/application/service/DeliveryCommandServiceImpl.java
  src/main/java/com/harusari/chainware/delivery/exception/DeliveryErrorCode.java
  src/main/java/com/harusari/chainware/order/command/application/service/OrderCommandServiceImpl.java
  src/test/java/com/harusari/chainware/delivery/command/application/controller/DeliveryCommandControllerTest.java
  src/test/java/com/harusari/chainware/delivery/command/application/service/DeliveryCommandServiceImplTest.java
Labels: ✔️ 테스트, 🔨 수정

#62 feat: 창고 관리 기능 및 테스트코드 작성
  src/main/java/com/harusari/chainware/config/security/SecurityConfig.java
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/warehouse/command/application/controller/WarehouseCommandController.java
  src/main/java/com/harusari/chainware/warehouse/command/application/dto/request/WarehouseInventoryCreateRequest.java
  src/main/java/com/harusari/chainware/warehouse/command/application/dto/request/WarehouseInventoryUpdateRequest.java
  src/main/java/com/harusari/chainware/warehouse/command/application/dto/request/WarehouseUpdateRequest.java
  src/main/java/com/harusari/chainware/warehouse/exception/WarehouseErrorCode.java
  src/test/java/com/harusari/chainware/warehouse/command/application/controller/WarehouseCommandControllerTest.java
  src/test/java/com/harusari/chainware/warehouse/command/application/service/WarehouseCommandServiceImplTest.java
Labels: ✔️ 테스트, 🔨 수정

#64 feat: 회원 정보 수정 기능 구현
  src/main/java/com/harusari/chainware/member/command/application/controller/MemberCommandController.java
  src/main/java/com/harusari/chainware/member/command/application/dto/request/UpdateMemberRequest.java
  src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandService.java
  src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandServiceImpl.java
  src/main/java/com/harusari/chainware/member/command/domain/aggregate/Member.java
  src/main/java/com/harusari/chainware/member/command/domain/repository/MemberCommandRepository.java
Labels: 🤖 기능

#67 fix: 동일 경로에 대해 다중 권한 개별 등록 시 발생하는 Access Denied 문제 수정
  src/main/java/com/harusari/chainware/config/security/AccessType.java
  src/main/java/com/harusari/chainware/config/security/SecurityConfig.java
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
Labels: 🐞 버그

#74 refactor: MapStruct 불필요한 옵션 제거 및 디렉토리명을 mapper에서 mapstruct으로 변경
  src/main/java/com/harusari/chainware/franchise/command/application/service/FranchiseCommandServiceImpl.java
  src/main/java/com/harusari/chainware/franchise/common/mapstruct/FranchiseMapStruct.java
  src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandServiceImpl.java
  src/main/java/com/harusari/chainware/member/common/mapstruct/MemberMapStruct.java
  src/main/java/com/harusari/chainware/vendor/command/application/service/VendorCommandServiceImpl.java
  src/main/java/com/harusari/chainware/vendor/common/mapstruct/VendorMapStruct.java
  src/main/java/com/harusari/chainware/warehouse/command/application/controller/WarehouseInventorySnapshotTestController.java
  src/main/java/com/harusari/chainware/warehouse/command/application/service/InventorySnapshotSchedulerImpl.java
  src/main/java/com/harusari/chainware/warehouse/command/mapper/WarehouseInventorySnapshotQueryMapper.java
  src/main/java/com/harusari/chainware/warehouse/common/mapstruct/WarehouseMapStruct.java
  src/main/resources/mappers/warehouse/WarehouseInventorySnapshotQueryMapper.xml
Labels: ♻️ 리팩토링

#73 feat : 예외처리 코드 수정 및 품의 / 발주 수정 기능 구현
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/exception/purchase/PurchaseOrderErrorCode.java
  src/main/java/com/harusari/chainware/exception/purchase/PurchaseOrderException.java
  src/main/java/com/harusari/chainware/exception/purchase/handler/PurchaseOrderExceptionHandler.java
  src/main/java/com/harusari/chainware/exception/requisition/RequisitionErrorCode.java
  src/main/java/com/harusari/chainware/exception/requisition/RequisitionException.java
  src/main/java/com/harusari/chainware/exception/requisition/handler/requisitionExceptionHandler.java
  src/main/java/com/harusari/chainware/purchase/command/application/controller/PurchaseOrderCommandController.java
  src/main/java/com/harusari/chainware/purchase/command/application/dto/request/ApprovePurchaseOrderRequest.java
  src/main/java/com/harusari/chainware/purchase/command/application/dto/request/CancelPurchaseOrderRequest.java
  src/main/java/com/harusari/chainware/purchase/command/application/dto/request/PurchaseOrderItemRequest.java
  src/main/java/com/harusari/chainware/purchase/command/application/dto/request/RejectPurchaseOrderRequest.java
  src/main/java/com/harusari/chainware/purchase/command/application/dto/request/UpdatePurchaseOrderRequest.java
  src/main/java/com/harusari/chainware/purchase/command/application/service/PurchaseOrderCommandService.java
  src/main/java/com/harusari/chainware/purchase/command/application/service/PurchaseOrderCommandServiceImpl.java
  src/main/java/com/harusari/chainware/purchase/command/domain/aggregate/PurchaseOrder.java
  src/main/java/com/harusari/chainware/purchase/command/domain/repository/PurchaseOrderDetailRepository.java
  src/main/java/com/harusari/chainware/purchase/query/controller/PurchaseOrderQueryController.java
  src/main/java/com/harusari/chainware/purchase/query/service/PurchaseOrderQueryServiceImpl.java
  src/main/java/com/harusari/chainware/requisition/command/application/controller/RequisitionCommandController.java
  src/main/java/com/harusari/chainware/requisition/command/application/dto/request/UpdateRequisitionRequest.java
  src/main/java/com/harusari/chainware/requisition/command/application/service/RequisitionCommandService.java
  src/main/java/com/harusari/chainware/requisition/command/application/service/RequisitionCommandServiceImpl.java
  src/main/java/com/harusari/chainware/requisition/command/domain/aggregate/Requisition.java
  src/main/java/com/harusari/chainware/requisition/command/domain/repository/RequisitionDetailRepository.java
  src/main/java/com/harusari/chainware/requisition/query/controller/RequisitionQueryController.java
  src/main/java/com/harusari/chainware/requisition/query/service/RequisitionQueryServiceImpl.java
  src/main/resources/mappers/purchase_order/PurchaseOrderQueryMapper.xml
Labels: 🤖 기능

#70 feat: 제품 카테고리, 제품 마스터 조회 기능 구현
  src/main/java/com/harusari/chainware/category/query/controller/CategoryQueryController.java
  src/main/java/com/harusari/chainware/category/query/dto/request/CategoryByTopCategoryRequest.java
  src/main/java/com/harusari/chainware/category/query/dto/response/CategoryDetailResponse.java
  src/main/java/com/harusari/chainware/category/query/dto/response/CategoryResponse.java
  src/main/java/com/harusari/chainware/category/query/dto/response/CategoryWithProductsResponse.java
  src/main/java/com/harusari/chainware/category/query/dto/response/TopCategoryDetailResponse.java
  src/main/java/com/harusari/chainware/category/query/dto/response/TopCategoryOnlyResponse.java
  src/main/java/com/harusari/chainware/category/query/dto/response/TopCategoryResponse.java
  src/main/java/com/harusari/chainware/category/query/mapper/CategoryQueryMapper.java
  src/main/java/com/harusari/chainware/category/query/service/CategoryQueryService.java
  src/main/java/com/harusari/chainware/category/query/service/CategoryQueryServiceImpl.java
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/product/query/controller/ProductQueryController.java
  src/main/java/com/harusari/chainware/product/query/dto/response/ProductDto.java
  src/main/java/com/harusari/chainware/product/query/mapper/ProductMapper.java
  src/main/java/com/harusari/chainware/product/query/service/ProductQueryService.java
  src/main/java/com/harusari/chainware/product/query/service/ProductQueryServiceImpl.java
  src/main/resources/mappers/category/CategoryQueryMapper.xml
  src/main/resources/mappers/contract/ContractQueryMapper.xml
  src/main/resources/mappers/product/ProductQueryMapper.xml
Labels: 🤖 기능

#80 refactor: MapStruct 매핑 시 unmapped 경고 무시하도록 설정 변경
  src/main/java/com/harusari/chainware/franchise/common/mapstruct/FranchiseMapStruct.java
  src/main/java/com/harusari/chainware/member/common/mapstruct/MemberMapStruct.java
  src/main/java/com/harusari/chainware/product/command/application/service/ProductCommandServiceImpl.java
  src/main/java/com/harusari/chainware/product/common/mapstruct/ProductMapStruct.java
  src/main/java/com/harusari/chainware/vendor/common/mapstruct/VendorMapStruct.java
  src/main/java/com/harusari/chainware/warehouse/common/mapstruct/WarehouseMapStruct.java
Labels: ♻️ 리팩토링

#83 feat: 배송 기본 조회 기능 구현
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/delivery/query/controller/DeliveryQueryController.java
  src/main/java/com/harusari/chainware/delivery/query/dto/request/DeliverySearchRequest.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryDetailInfo.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryDetailResponse.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryOrderInfo.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryProductInfo.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliverySearchResponse.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/FranchiseInfo.java
  src/main/java/com/harusari/chainware/delivery/query/dto/response/WarehouseInfo.java
  src/main/java/com/harusari/chainware/delivery/query/repository/DeliveryQueryRepository.java
  src/main/java/com/harusari/chainware/delivery/query/repository/DeliveryQueryRepositoryCustom.java
  src/main/java/com/harusari/chainware/delivery/query/repository/DeliveryQueryRepositoryImpl.java
  src/main/java/com/harusari/chainware/delivery/query/service/DeliveryQueryService.java
  src/main/java/com/harusari/chainware/delivery/query/service/DeliveryQueryServiceImpl.java
Labels: 🤖 기능

#84 feat: 거래처 별 제품 계약 정보 조회 기능 구현
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/contract/query/controller/VendorProductContractController.java
  src/main/java/com/harusari/chainware/contract/query/dto/response/VendorProductContractDto.java
  src/main/java/com/harusari/chainware/contract/query/mapper/VendorProductContractMapper.java
  src/main/java/com/harusari/chainware/contract/query/service/VendorProductContractService.java
  src/main/java/com/harusari/chainware/contract/query/service/VendorProductContractServiceImpl.java
  src/main/java/com/harusari/chainware/product/query/controller/ProductQueryController.java
  src/main/java/com/harusari/chainware/product/query/mapper/ProductQueryMapper.java
  src/main/java/com/harusari/chainware/product/query/service/ProductQueryServiceImpl.java
  src/main/resources/mappers/category/CategoryQueryMapper.xml
  src/main/resources/mappers/product/ProductQueryMapper.xml
Labels: 🤖 기능

#90 feat : 발주 출고 처리 기능 구현 / Access Denied 에러 메세지 커스텀
  src/main/java/com/harusari/chainware/auth/jwt/RestAccessDeniedHandler.java
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/exception/purchase/PurchaseOrderErrorCode.java
  src/main/java/com/harusari/chainware/purchase/command/application/controller/PurchaseOrderCommandController.java
  src/main/java/com/harusari/chainware/purchase/command/application/service/PurchaseOrderCommandService.java
  src/main/java/com/harusari/chainware/purchase/command/application/service/PurchaseOrderCommandServiceImpl.java
  src/main/java/com/harusari/chainware/purchase/command/domain/aggregate/PurchaseOrder.java
  src/main/java/com/harusari/chainware/purchase/command/domain/aggregate/PurchaseOrderStatus.java
  src/main/java/com/harusari/chainware/purchase/query/controller/PurchaseOrderQueryController.java
  src/main/java/com/harusari/chainware/requisition/command/application/controller/RequisitionCommandController.java
  src/main/java/com/harusari/chainware/requisition/query/controller/RequisitionQueryController.java
  src/main/java/com/harusari/chainware/vendor/query/dto/VendorDetailDto.java
  src/main/resources/mappers/vendor/VendorQueryMapper.xml
Labels: ♻️ 리팩토링, 🤖 기능

#98 feat: 가맹점 상태를 변경하는 기능 구현
  src/main/java/com/harusari/chainware/franchise/command/application/dto/request/UpdateFranchiseRequest.java
  src/main/java/com/harusari/chainware/franchise/command/application/service/FranchiseCommandServiceImpl.java
  src/main/java/com/harusari/chainware/franchise/command/domain/aggregate/Franchise.java
  src/main/java/com/harusari/chainware/franchise/command/domain/aggregate/FranchiseStatus.java
  src/main/java/com/harusari/chainware/franchise/command/domain/repository/FranchiseCommandRepositoryImpl.java
Labels: 🤖 기능

#100 feat: 가맹점 목록 조회 기능 구현
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/franchise/command/application/controller/FranchiseCommandController.java
  src/main/java/com/harusari/chainware/franchise/query/controller/FranchiseQueryController.java
  src/main/java/com/harusari/chainware/franchise/query/dto/request/FranchiseSearchRequest.java
  src/main/java/com/harusari/chainware/franchise/query/dto/resposne/FranchiseSearchResponse.java
  src/main/java/com/harusari/chainware/franchise/query/repository/FranchiseQueryRepository.java
  src/main/java/com/harusari/chainware/franchise/query/repository/FranchiseQueryRepositoryCustom.java
  src/main/java/com/harusari/chainware/franchise/query/repository/FranchiseQueryRepositoryImpl.java
  src/main/java/com/harusari/chainware/franchise/query/service/FranchiseQueryService.java
  src/main/java/com/harusari/chainware/franchise/query/service/FranchiseQueryServiceImpl.java
Labels: 🤖 기능

#102 feat: 가맹점 상세 조회 기능 구현
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/franchise/query/controller/FranchiseQueryController.java
  src/main/java/com/harusari/chainware/franchise/query/dto/resposne/FranchiseSearchDetailResponse.java
  src/main/java/com/harusari/chainware/franchise/query/repository/FranchiseQueryRepositoryCustom.java
  src/main/java/com/harusari/chainware/franchise/query/repository/FranchiseQueryRepositoryImpl.java
  src/main/java/com/harusari/chainware/franchise/query/service/FranchiseQueryService.java
  src/main/java/com/harusari/chainware/franchise/query/service/FranchiseQueryServiceImpl.java
Labels: 🤖 기능

#108 docs: 카테고리, 제품, 거래처별 제품 컨트롤러에 Swagger 문서화 어노테이션 추가
  src/main/java/com/harusari/chainware/category/command/application/controller/CategoryCommandController.java
  src/main/java/com/harusari/chainware/category/command/application/controller/TopCategoryCommandController.java
  src/main/java/com/harusari/chainware/category/query/controller/CategoryQueryController.java
  src/main/java/com/harusari/chainware/contract/command/application/controller/ContractCommandController.java
  src/main/java/com/harusari/chainware/contract/command/application/dto/request/ContractCreateRequest.java
  src/main/java/com/harusari/chainware/contract/command/application/dto/request/ContractUpdateRequest.java
  src/main/java/com/harusari/chainware/contract/query/controller/VendorProductContractQueryController.java
  src/main/java/com/harusari/chainware/exception/contract/handler/ContractExceptionHandler.java
  src/main/java/com/harusari/chainware/product/command/application/controller/ProductCommandController.java
  src/main/java/com/harusari/chainware/product/command/application/dto/request/ProductCreateRequest.java
  src/main/java/com/harusari/chainware/product/command/application/dto/request/ProductUpdateRequest.java
  src/main/java/com/harusari/chainware/product/query/controller/ProductQueryController.java
  src/test/java/com/harusari/chainware/category/command/application/controller/CategoryCommandControllerTest.java
  src/test/java/com/harusari/chainware/category/command/application/controller/TopCategoryCommandControllerTest.java
  src/test/java/com/harusari/chainware/category/command/application/service/CategoryCommandServiceImplTest.java
  src/test/java/com/harusari/chainware/category/command/application/service/TopCategoryCommandServiceImplTest.java
  src/test/java/com/harusari/chainware/contract/command/application/controller/ContractCommandControllerTest.java
  src/test/java/com/harusari/chainware/contract/command/application/service/ContractServiceImplTest.java
  src/test/java/com/harusari/chainware/contract/query/controller/VendorProductContractQueryControllerTest.java
  src/test/java/com/harusari/chainware/contract/query/service/VendorProductContractServiceImplTest.java
  src/test/java/com/harusari/chainware/product/command/application/controller/ProductCommandControllerTest.java
  src/test/java/com/harusari/chainware/product/command/application/service/ProductCommandServiceImplTest.java
  src/test/java/com/harusari/chainware/product/query/controller/ProductQueryControllerTest.java
  src/test/java/com/harusari/chainware/product/query/service/ProductQueryServiceImplTest.java
Labels: ♻️ 리팩토링, 📝 문서

#113 feat: 주문 등록 및 승인 로직 수정
  src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
  src/main/java/com/harusari/chainware/delivery/command/application/service/DeliveryCommandServiceImpl.java
  src/main/java/com/harusari/chainware/delivery/command/domain/aggregate/DeliveryMethod.java
  src/main/java/com/harusari/chainware/disposal/command/application/service/DisposalCommandServiceImpl.java
  src/main/java/com/harusari/chainware/disposal/query/service/DisposalQueryServiceImpl.java
  src/main/java/com/harusari/chainware/order/command/application/controller/OrderCommandController.java
  src/main/java/com/harusari/chainware/order/command/application/dto/request/OrderApproveRequest.java
  src/main/java/com/harusari/chainware/order/command/application/service/OrderCommandService.java
  src/main/java/com/harusari/chainware/order/command/application/service/OrderCommandServiceImpl.java
  src/main/java/com/harusari/chainware/order/query/controller/OrderQueryController.java
  src/main/java/com/harusari/chainware/order/query/controller/OrderWarehouseQueryController.java
  src/main/java/com/harusari/chainware/order/query/dto/response/AvailableWarehouseResponse.java
  src/main/java/com/harusari/chainware/order/query/service/OrderWarehouseQueryService.java
  src/main/java/com/harusari/chainware/order/query/service/OrderWarehouseQueryServiceImpl.java
  src/main/java/com/harusari/chainware/takeback/command/application/service/TakeBackCommandServiceImpl.java
  src/main/java/com/harusari/chainware/warehouse/command/application/service/WarehouseCommandServiceImpl.java
  src/main/java/com/harusari/chainware/warehouse/command/domain/repository/WarehouseInventoryRepository.java
  src/main/java/com/harusari/chainware/warehouse/command/domain/repository/WarehouseRepository.java
  src/main/java/com/harusari/chainware/warehouse/command/infrastructure/repository/JpaWarehouseInventoryRepository.java
  src/main/java/com/harusari/chainware/warehouse/command/infrastructure/repository/JpaWarehouseRepository.java
  src/test/java/com/harusari/chainware/delivery/command/application/service/DeliveryCommandServiceImplTest.java
  src/test/java/com/harusari/chainware/order/command/application/controller/OrderCommandControllerTest.java
  src/test/java/com/harusari/chainware/order/command/application/service/OrderCommandServiceImplTest.java
  src/test/java/com/harusari/chainware/statistics/query/service/disposal/DisposalRateStatisticsQueryServiceImplTest.java
  src/test/java/com/harusari/chainware/statistics/query/service/purchaseOrder/PurchaseOrderStatisticsQueryServiceImplTest.java
  src/test/java/com/harusari/chainware/statistics/query/service/storeOrder/StoreOrderStatisticsQueryServiceImplTest.java
  src/test/java/com/harusari/chainware/warehouse/command/application/service/WarehouseCommandServiceImplTest.java
Labels: ♻️ 리팩토링, 🤖 기능

#116 test: 가맹점 테스트 코드 작성
  src/test/java/com/harusari/chainware/franchise/command/application/controller/FranchiseCommandControllerTest.java
  src/test/java/com/harusari/chainware/franchise/command/application/service/FranchiseCommandServiceImplTest.java
  src/test/java/com/harusari/chainware/franchise/command/domain/aggregate/FranchiseTest.java
  src/test/java/com/harusari/chainware/franchise/query/controller/FranchiseQueryControllerTest.java
  src/test/java/com/harusari/chainware/franchise/query/service/FranchiseQueryServiceImplTest.java
Labels: ✔️ 테스트

#118 test: FranchiseCommandServiceImplTest에서 MapStruct 실제 매핑 테스트로 변경
  src/test/java/com/harusari/chainware/franchise/command/application/service/FranchiseCommandServiceImplTest.java
Labels: ♻️ 리팩토링, ✔️ 테스트

#112 test : 카테고리, 제품, 거래처별 제품 계약 테스트 코드 작성
  src/main/java/com/harusari/chainware/category/command/application/controller/CategoryCommandController.java
  src/main/java/com/harusari/chainware/category/command/application/controller/TopCategoryCommandController.java
  src/main/java/com/harusari/chainware/category/command/application/service/CategoryCommandServiceImpl.java
  src/main/java/com/harusari/chainware/category/command/application/service/TopCategoryCommandServiceImpl.java
  src/main/java/com/harusari/chainware/category/command/domain/repository/CategoryRepository.java
  src/main/java/com/harusari/chainware/category/command/domain/repository/TopCategoryRepository.java
  src/main/java/com/harusari/chainware/category/command/infrastructure/JpaCategoryRepository.java
  src/main/java/com/harusari/chainware/category/command/infrastructure/JpaTopCategoryRepository.java
  src/main/java/com/harusari/chainware/category/query/controller/CategoryQueryController.java
  src/main/java/com/harusari/chainware/contract/command/application/controller/ContractCommandController.java
  src/main/java/com/harusari/chainware/contract/command/infrastructure/JpaContractRepository.java
  src/main/java/com/harusari/chainware/contract/query/controller/VendorProductContractQueryController.java
  src/main/java/com/harusari/chainware/contract/query/service/VendorProductContractServiceImpl.java
  src/main/resources/mappers/product/ProductQueryMapper.xml
  src/test/java/com/harusari/chainware/category/command/application/controller/CategoryCommandControllerTest.java
  src/test/java/com/harusari/chainware/category/command/application/controller/TopCategoryCommandControllerTest.java
  src/test/java/com/harusari/chainware/category/command/application/service/CategoryCommandServiceImplTest.java
  src/test/java/com/harusari/chainware/category/command/application/service/TopCategoryCommandServiceImplTest.java
  src/test/java/com/harusari/chainware/category/query/controller/CategoryQueryControllerTest.java
  src/test/java/com/harusari/chainware/category/query/service/CategoryQueryServiceImplTest.java
  src/test/java/com/harusari/chainware/contract/command/application/controller/ContractCommandControllerTest.java
  src/test/java/com/harusari/chainware/contract/command/application/service/ContractServiceImplTest.java
  src/test/java/com/harusari/chainware/contract/query/controller/VendorProductContractQueryControllerTest.java
  src/test/java/com/harusari/chainware/contract/query/service/VendorProductContractServiceImplTest.java
  src/test/java/com/harusari/chainware/product/command/application/controller/ProductCommandControllerTest.java
  src/test/java/com/harusari/chainware/product/command/application/service/ProductCommandServiceImplTest.java
  src/test/java/com/harusari/chainware/product/query/controller/ProductQueryControllerTest.java
  src/test/java/com/harusari/chainware/product/query/service/ProductQueryServiceImplTest.java
Labels: ✔️ 테스트
